trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/UnitTest1.cs'
  project: '**/playwrightDemo.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet Tool nuInstaller'

- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true # Required for preview versions
- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime
- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest
- task: DotNetCoreCLI@2
  displayName: Install Playwright CLI
  inputs:
    command: custom
    custom: 'tool '
    arguments: install Microsoft.Playwright.CLI
- task: NuGetCommand@2
  name: 'NuGetToolRestore' 
  displayName: 'NuGet Tool Restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    
- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--no-restore -c Release /p:Platform=x64 /p:Version=$(Build.BuildNumber)'